// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viagenstka.Data;

#nullable disable

namespace Viagenstka.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Viagenstka.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cpf");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.Property<string>("nomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nomeCompleto");

                    b.HasKey("Id");

                    b.ToTable("cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "122.122.133-33",
                            Telefone = "(21)99797-4565",
                            Url = "https://fv5-2.failiem.lv/down.php?i=9zh6bmhrnj&view",
                            nomeCompleto = "Thamires Almeida"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "178.178.177-78",
                            Telefone = "(87)3184-2819",
                            Url = "https://fv5-2.failiem.lv/down.php?i=3g2ng3ugd2&view",
                            nomeCompleto = "Ana Santos"
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "769.290.670-08",
                            Telefone = "(21)92555-2381",
                            Url = "https://fv5-2.failiem.lv/down.php?i=dv3vdcf54z&view",
                            nomeCompleto = "Angela Rocha"
                        },
                        new
                        {
                            Id = 4,
                            Cpf = "791.555.800-50",
                            Telefone = "(18)93571-6471",
                            Url = "https://fv5-2.failiem.lv/down.php?i=eqxha3jn88&view",
                            nomeCompleto = "José Carlos"
                        },
                        new
                        {
                            Id = 5,
                            Cpf = "532.284.780-41",
                            Telefone = "(13)92741-3363",
                            Url = "https://fv5-2.failiem.lv/down.php?i=8s9g72yxj9&view",
                            nomeCompleto = "Vitor Alves"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
